### PR TITLE
 change UI

### PR DESCRIPTION
**Pull request by AnhKhoi0310**
Change RiskChat UI, fix gemini Bug

### CODE REVIEW

**Comment by AnhKhoi0310** [comment]
Able to go through all the netlify tests

**Comment by AnhKhoi0310** [comment]
able to go throught tests

**Comment by AnhKhoi0310** [comment]
able to go throught tests

**Comment by AnhKhoi0310** [comment]
able to go throught tests

**Comment by DungLe2911** [comment]
@AnhKhoi0310 conflict trong news vue nha em. fix conflict xong up lên lại rồi anh merge cho'

**Pull request closed without merging**
